[package]
name = "av-stream-info-rust"
version = "0.7.3"
authors = ["segler <segler_alex@web.de>"]
repository = "https://github.com/segler-alex/av-stream-info-rust"
categories = ["network-programming", "parsing"]
license = "MIT"
description = "Analyze a http/https internet address and display information if an audio or video stream has been found. All information is extracted from metainformation."
readme = "README.md"
edition = "2018"

[dependencies]
colored = "1.9.3"
env_logger = "0.7.1"
hls_m3u8 = "0.2.1"
log = "0.4.8"
native-tls = "0.2.4"
playlist-decoder = "0.8.0"
reqwest = { version = "0.10.6", features = ["blocking", "trust-dns"] }
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1.0.55"
tree_magic = "0.2.3"
url = "2.1.1"