[package]
name = "av-stream-info-rust"
version = "0.5.1"
authors = ["segler <segler_alex@web.de>"]
repository = "https://github.com/segler-alex/av-stream-info-rust"
categories = ["network-programming", "parsing"]
license = "MIT"
description = "Analyze a http/https internet address and display information if an audio or video stream has been found. All information is extracted from metainformation."

[dependencies]
colored = "1.8.0"
env_logger = "0.6.2"
hls_m3u8 = "0.1.4"
log = "0.4.8"
native-tls = "0.2.3"
playlist-decoder = "0.7.1"
tree_magic = "0.2.1"
url = "2.1.0"